---
- name: Install required packages
  dnf:
    name:
      - podman
      - python3-pip
      - firewalld
    state: present
  become: yes

- name: Start and enable podman socket
  systemd:
    name: podman.socket
    state: started
    enabled: yes
  become: yes