all:
  children:
    postgres_cluster:
      hosts:
        pg1:
          ansible_host: 192.168.200.10
          postgres_role: primary
        pg2:
          ansible_host: 192.168.200.20
          postgres_role: replica
      vars:
        ansible_user: seletz
        ansible_ssh_private_key_file: ~/.ssh/podman-postgres-ha-experiment
        ansible_python_interpreter: /usr/bin/python3
