---
- name: Setup PostgreSQL HA Cluster
  hosts: postgres_cluster
  become: yes
  
  roles:
    - podman-setup
    - postgres-base

- name: Configure PostgreSQL Primary
  hosts: pg1
  become: yes
  
  roles:
    - postgres-primary

- name: Configure PostgreSQL Replica
  hosts: pg2
  become: yes
  
  roles:
    - postgres-replica