# PostgreSQL Configuration
postgres_version: "16"
postgres_image: "docker.io/library/postgres:{{ postgres_version }}"
postgres_database: "testdb"
postgres_user: "testuser"
postgres_password: "securepass123"
postgres_replication_user: "replicator"
postgres_replication_password: "replicatorpass123"

# Networking
postgres_port: 5432
primary_host: "192.168.200.10"
replica_host: "192.168.200.20"

# PostgreSQL System Configuration
postgres_home_dir: "/var/lib/postgresql"
postgres_data_dir: "{{ postgres_home_dir }}/data"

# Podman Configuration
postgres_container_name: "postgres-ha"