# PostgreSQL Configuration
postgres_version: "16"
postgres_image: "docker.io/library/postgres:{{ postgres_version }}"
postgres_user: "postgres"
postgres_password: "securepass123"
postgres_replication_user: "replicator"
postgres_replication_password: "replicatorpass123"
postgres_uid: 26
postgres_gid: 26

# Networking
postgres_port: 5432
primary_host: "192.168.200.10"
replica_host: "192.168.200.20"
database_network: "192.168.200.0/24"

# PostgreSQL System Configuration
postgres_home_dir: "/var/lib/postgresql"
postgres_data_dir: "{{ postgres_home_dir }}/data"

# Podman Configuration
postgres_container_name: "postgres-ha"